### ISSUE TITLE
Post install, spits out the following error while using

### ISSUE THREAD

**Issue by sandeepwadhwa-ai** [cansik/mediapipe-silicon#4]
objc[91870]: Class CaptureDelegate is implemented in both /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x127072538) and /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_videoio.3.4.16.dylib (0x1525d0860). One of the two will be used. Which one is undefined.

objc[91870]: Class CVWindow is implemented in both /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x127072588) and /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x1518a0a68). One of the two will be used. Which one is undefined.

objc[91870]: Class CVView is implemented in both /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x1270725b0) and /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x1518a0a90). One of the two will be used. Which one is undefined.

objc[91870]: Class CVSlider is implemented in both /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x1270725d8) and /Users/sandy/miniforge3/envs/virtualmouse/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x1518a0ab8). One of the two will be used. Which one is undefined.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

CV2 and MediaPipe have the same class names.

**Comment by cansik** [comment]
This is just a warning and can be ignored. It has to do with the OpenCV which is bundled in `opencv-python` and `mediapipe`. Maybe it would be possible to remove the libraries, but for now they are bundled by the [delocator tool](https://github.com/matthew-brett/delocate).

**Comment by sandeepwadhwa-ai** [comment]
Yes that is true, it is a warning and not an error. I was attributing some other error in my program to this. Anyways thanks for pointing out that it is a warning. Should have realised it myself!!! (One of those bad days.....). Fixed the error and let this warning remain as it is . :-)
