### ISSUE TITLE
No attribute 'iris'

### ISSUE THREAD

**Issue by lakshyabajaj14** [cansik/mediapipe-silicon#6]
Getting the following error while running the mediapipe iris code:
  
mp_iris = mp.solutions.iris
AttributeError: module 'mediapipe.python.solutions' has no attribute 'iris'

I am using python 3.8 with mediapipe-silicon 0.8.10.1 on apple M1

**Comment by cansik** [comment]
Iris detection is not part of the default python module as far as I know: https://google.github.io/mediapipe/solutions/solutions.html

You would have to build the calculators for that manually.
