### ISSUE TITLE
Please support 0.8.11 to avoid model download error

### ISSUE THREAD

**Issue by sikang99** [cansik/mediapipe-silicon#7]
Current version 0.8.10.1 causes model download error because of change for download position as following.
https://github.com/google/mediapipe/releases/tag/v0.8.11

**Comment by cansik** [comment]
Could you tryout the pre-built wheels from [here](https://github.com/cansik/mediapipe-silicon/releases/tag/v0.8.11) and give me feedback if everything works again?

**Comment by webnard** [comment]
@cansik Not OP, but the new wheel seems to fix the problem 👍

**Comment by cansik** [comment]
@webnard Thank you for the feedback - I've released the new version on [PyPi](https://pypi.org/project/mediapipe-silicon/0.8.11/).
